In [1]:
# import the library
import numpy as np

In [2]:
# initialize a numpy array representing a vector of 5 integer elements
A = np.array([1, 2, 3, 4, 5], dtype=int)
print(A)

[1 2 3 4 5]


In [3]:
# if you don't specify the dtype, numpy will deduce it from the values present in the table
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
print(my_array.dtype)

[1 2 3 4 5]
int64


In [4]:
my_array = np.array([1, blavla, 3, 4, 4.56])
print(my_array)
print(my_array.dtype)

NameError: name 'blavla' is not defined

In [ ]:
# You can use nested lists to initialize a matrix or a tensor of a higer rank:
my_matrix = np.array([[1, 2, 3],
                      [5, 6, 7]])
print(my_matrix)
print("Shape of the matrix:", my_matrix.shape)

In [ ]:
my_tensor = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]]])
print(my_tensor)
print("Shape of the tensor", my_tensor.shape)

In [ ]:
# Representation of a vector v in numpy
v_vec = np.array([2, 3, 5])
print(v_vec)
print("Shape of v", v_vec.shape)

In [ ]:
# Representation of A (Matrix)
A_mat = np.array([[1, 2],
                  [-1, 3],
                  [0, 4]])
print(A_mat)
print("Shape of A:", A_mat.shape)

In [ ]:
# Vector Operations
# Example with numpy

u_vec = np.array([6, 0, 2])
v_vec = np.array([-1, -2, 3])
print("vector u:", u_vec.shape)
print(u_vec)
print("vector v:", v_vec.shape)
print (v_vec)
print()

#T The operators +, - and * work with my numpy arrays!
print("addition of u and v:")
print(u_vec + v_vec)
print()
print("substraction of u and v:")
print(u_vec - v_vec)
print()
print("scaling of u by a factor 3:")
print(3*u_vec)


In [ ]:
# Example with numpy
print("vector u:")
print(u_vec)
print("vector v:")
print(v_vec)
print()
 
# Norm of vectors
print("-- norm of u and v --")
print("Norm of u:")
print(np.linalg.norm(u_vec)) # use norm function from the linalg module
print("Norm of v:")
print(np.linalg.norm(v_vec))
print()

# Dot-product of u and v
print("-- dot-product of u and v --")
print(u_vec.dot(v_vec))

In [ ]:
# Matrix operations
A_mat = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

B_mat = np.array([[10, 10, 10],
                  [20, 20, 20],
                  [30, 30, 30]])

print("matrix A:")
print(A_mat)
print("matrix B:")
print(B_mat)
print()

print("Addition of A and B:")
print(A_mat + B_mat) # the + operator also works for any rank of numpy array : vectors, matrices ans tensors !
print()

print("Substraction of A and B:")
print(A_mat - B_mat) # same for the - operator
print()

print("Scaling of A by a factor 2:")
print(2*A_mat) # same for the * operator


In [ ]:
# Matrix product
# Example with numpy
print("matrix A:")
print(A_mat)
print("matrix B:")
print(B_mat)
print()

# The @ operator represents matrix multiplication
print("-- With @ operator --")
print("Matrix product AB: ")
print(A_mat @ B_mat)
print()
print("Matrix product BA: ")
print(B_mat @ A_mat)
print()

# Another way of computing matrix multiplication is to use the dot product !
print("-- With .dot function --")
print("Matrix product AB: ")
print(A_mat.dot(B_mat))
print()
print("Matrix product BA: ")
print(B_mat.dot(A_mat))
print()


In [ ]:
# Matrix-vector product
# Example with numpy
C_mat = np.array([[1, 2],
                 [3, 4],
                  [5, 6]])
x_vec = np.array([5, -2])

print("matrix C of shape ", C_mat.shape)
print(C_mat)
print()
print("vector x of shape ", x_vec.shape)
print(x_vec)
print()

# Compute matrix-vector product
y_vec = C_mat @ x_vec
print("The product Cx gives another vector y of shape ", y_vec.shape)
print(y_vec)

In [ ]:
# Matrix transpose
# Example with numpy
print("matrix A:")
print(A_mat)
print("Transpose of A:")
print(A_mat.T) # .T allows to transpose a numpy array
print()
print("matrix B:")
print(B_mat)
print("Transpose of B:")
print(B_mat.T)
print()

print("Tranpose(AB):")
print((A_mat @ B_mat).T)
print()

print("Tranpose(B) @ Tranpose(A):")
print(B_mat.T @ A_mat.T)

In [ ]:
# Identity matrix
# identity matrix in numpy
id_mat = np.identity(3, dtype = 'int')
print("identity matrix I: ")
print(id_mat)
print("matrix A:")
print(A_mat)
print()

print("IA:")
print(id_mat @ A_mat)
print("AI:")
print(A_mat @ id_mat)

In [5]:
# Inverse of a matrix
# Example with numpy
print("matrix D:")
D_mat = np.array([[3, 0, 2],
                  [2, 0, -2],
                  [0, 1, 1]], dtype = 'int')
print(D_mat)
print()

print("Inverse of D:")
D_mat_inv = np.linalg.inv(D_mat)
print(D_mat_inv)
print()

print("Let's check the matrix product of D with its inverse:")
print((D_mat_inv @ D_mat).round(2))
print()
print((D_mat @ D_mat_inv).round(2))

matrix D:
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

Inverse of D:
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]

Let's check the matrix product of D with its inverse:
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
# Orthogonality of matrices
# Example with numpy
U_mat = np.array([[2/3, -2/3, 1/3],
                  [1/3, 2/3, 2/3],
                  [2/3, 1/3, -2/3]])
print("Matrix U:")
print(U_mat)
print()

print("Tranpose of matrix U:")
print(U_mat.T)
print()

print("Matrix product of tranpose(U) and U:")
print((U_mat.T @ U_mat).round(2))

Matrix U:
[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]

Tranpose of matrix U:
[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]

Matrix product of tranpose(U) and U:
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [7]:
# Systems of lineat equations : Matrix representation
# Example with numpy
A_mat = np.array([[1, 2],
                  [3, 9]])
b_vec = np.array([5, 21])
print("Matrix A:")
print(A_mat)
print("Vector b:")
print(b_vec)
print()

## Method 1
print("-- Method 1 --")
# Compute inverse of matrix A
A_mat_inv = np.linalg.inv(A_mat)
# Solve equation
x_vec = A_mat_inv @ b_vec
print("Solution of equation Ax = b:")
print("x = ", x_vec)
print()

## Method 2 : with np.linalg.solve
print("-- Method 2 --")
x_vec = np.linalg.solve(A_mat, b_vec)
print("Solution of equation Ax = b:")
print("x = ", x_vec)

Matrix A:
[[1 2]
 [3 9]]
Vector b:
[ 5 21]

-- Method 1 --
Solution of equation Ax = b:
x =  [1. 2.]

-- Method 2 --
Solution of equation Ax = b:
x =  [1. 2.]


In [8]:
# Matrix diagonalization
# Example with numpy
A_mat = np.array([[3, 4, -2],
                  [1, 4, -1],
                  [2, 6, -1]])
print("Matrix A:")
print(A_mat)
print()

eigenvals, eigenvecs = np.linalg.eig(A_mat)
print("Eigenvalues of A:")
print(eigenvals)
print()
print("Eigenvectors of A:")
print(eigenvecs.round(3))
print()

print("Let's check the effect of A on its first eigenvector: ")
print(A_mat @ eigenvecs[:,0])
print("The above is equal to the eigenvector scaled by its eigenvalue (3):")
print(3*eigenvecs[:,0])

Matrix A:
[[ 3  4 -2]
 [ 1  4 -1]
 [ 2  6 -1]]

Eigenvalues of A:
[3. 2. 1.]

Eigenvectors of A:
[[-0.408  0.     0.707]
 [-0.408  0.447 -0.   ]
 [-0.816  0.894  0.707]]

Let's check the effect of A on its first eigenvector: 
[-1.22474487 -1.22474487 -2.44948974]
The above is equal to the eigenvector scaled by its eigenvalue (3):
[-1.22474487 -1.22474487 -2.44948974]
