In [1]:
# import the library
import numpy as np

In [2]:
# initialize a numpy array representing a vector of 5 integer elements
A = np.array([1, 2, 3, 4, 5], dtype=int)
print(A)

[1 2 3 4 5]


In [3]:
# if you don't specify the dtype, numpy will deduce it from the values present in the table
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
print(my_array.dtype)

[1 2 3 4 5]
int64


In [4]:
my_array = np.array([1, blavla, 3, 4, 4.56])
print(my_array)
print(my_array.dtype)

NameError: name 'blavla' is not defined

In [6]:
# You can use nested lists to initialize a matrix or a tensor of a higer rank:
my_matrix = np.array([[1, 2, 3],
                      [5, 6, 7]])
print(my_matrix)
print("Shape of the matrix:", my_matrix.shape)

[[1 2 3]
 [5 6 7]]
Shape of the matrix: (2, 3)


In [8]:
my_tensor = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]]])
print(my_tensor)
print("Shape of the tensor", my_tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of the tensor (2, 2, 3)


In [9]:
# Representation of a vector v in numpy
v_vec = np.array([2, 3, 5])
print(v_vec)
print("Shape of v", v_vec.shape)

[2 3 5]
Shape of v (3,)


In [10]:
# Representation of A (Matrix)
A_mat = np.array([[1, 2],
                  [-1, 3],
                  [0, 4]])
print(A_mat)
print("Shape of A:", A_mat.shape)

[[ 1  2]
 [-1  3]
 [ 0  4]]
Shape of A: (3, 2)


In [14]:
# Vector Operations
# Example with numpy

u_vec = np.array([6, 0, 2])
v_vec = np.array([-1, -2, 3])
print("vector u:", u_vec.shape)
print(u_vec)
print("vector v:", v_vec.shape)
print (v_vec)
print()

#T The operators +, - and * work with my numpy arrays!
print("addition of u and v:")
print(u_vec + v_vec)
print()
print("substraction of u and v:")
print(u_vec - v_vec)
print()
print("scaling of u by a factor 3:")
print(3*u_vec)


vector u: (3,)
[6 0 2]
vector v: (3,)
[-1 -2  3]

addition of u and v:
[ 5 -2  5]

substraction of u and v:
[ 7  2 -1]

scaling of u by a factor 3:
[18  0  6]


In [16]:
# Example with numpy
print("vector u:")
print(u_vec)
print("vector v:")
print(v_vec)
print()
 
# Norm of vectors
print("-- norm of u and v --")
print("Norm of u:")
print(np.linalg.norm(u_vec)) # use norm function from the linalg module
print("Norm of v:")
print(np.linalg.norm(v_vec))
print()

# Dot-product of u and v
print("-- dot-product of u and v --")
print(u_vec.dot(v_vec))

vector u:
[6 0 2]
vector v:
[-1 -2  3]

-- norm of u and v --
Norm of u:
6.324555320336759
Norm of v:
3.7416573867739413

-- dot-product of u and v --
0


In [17]:
# Matrix operations
A_mat = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

B_mat = np.array([[10, 10, 10],
                  [20, 20, 20],
                  [30, 30, 30]])

print("matrix A:")
print(A_mat)
print("matrix B:")
print(B_mat)
print()

print("Addition of A and B:")
print(A_mat + B_mat) # the + operator also works for any rank of numpy array : vectors, matrices ans tensors !
print()

print("Substraction of A and B:")
print(A_mat - B_mat) # same for the - operator
print()

print("Scaling of A by a factor 2:")
print(2*A_mat) # same for the * operator


matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B:
[[10 10 10]
 [20 20 20]
 [30 30 30]]

Addition of A and B:
[[11 12 13]
 [24 25 26]
 [37 38 39]]

Substraction of A and B:
[[ -9  -8  -7]
 [-16 -15 -14]
 [-23 -22 -21]]

Scaling of A by a factor 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [18]:
# Matrix product
# Example with numpy
print("matrix A:")
print(A_mat)
print("matrix B:")
print(B_mat)
print()

# The @ operator represents matrix multiplication
print("-- With @ operator --")
print("Matrix product AB: ")
print(A_mat @ B_mat)
print()
print("Matrix product BA: ")
print(B_mat @ A_mat)
print()

# Another way of computing matrix multiplication is to use the dot product !
print("-- With .dot function --")
print("Matrix product AB: ")
print(A_mat.dot(B_mat))
print()
print("Matrix product BA: ")
print(B_mat.dot(A_mat))
print()


matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix B:
[[10 10 10]
 [20 20 20]
 [30 30 30]]

-- With @ operator --
Matrix product AB: 
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Matrix product BA: 
[[120 150 180]
 [240 300 360]
 [360 450 540]]

-- With .dot function --
Matrix product AB: 
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Matrix product BA: 
[[120 150 180]
 [240 300 360]
 [360 450 540]]

