In [12]:
import numpy as np

In [13]:
# Initialization to 0 (matrix 3x4)
display(np.zeros((3,4)))

# Initialization to 1 (matrix 5x4)
display(np.ones((5,4)))

# Third order tensor (can be seen as 2 matrices 3x4)
np.ones((2,3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# Generates a list of numbers from 3.2 to 4.8 excluded with a step of 0.2.
np.arange(3.2, 4.8, 0.2)

array([3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6])

In [15]:
# Initialize an array from a user-defined function
def f(x, y):
    return 10*x+y

# Creating an array from the function from above
np.fromfunction(f,(5,4),dtype=int)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [16]:
# Accessing items in a multidimensional array
c = np.array([[0, 1, 2],
               [10, 12, 13],
               [100, 101, 102],
               [110, 112, 113]])

In [17]:
c[3, 2] # Accessing to the value contained in the 4th row, 3rd column, is accessed

np.int64(113)

In [18]:
c[1, 2]

np.int64(13)

In [19]:
# Creation of a third order tensor
c = np.array( [[[  0,  1,  2],
                 [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])
# sans ajout des [] la requête suivante génère une erreur, car elle cherche dans un array se 2 dimensions, or nous en indexons 3

In [20]:
c[0, 1, 2] # We access the value contained in the 2nd row, 3rd column of the first matrix

np.int64(13)

In [21]:
# Create matrix
c = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

In [22]:
# Iterate on the elements of the matrix

# Not recommanded (may be slow):
for row in c:
    for e in row:
        print(e)

print()
print('----------')
print()

# Better:
for e in c.flat:
    print(e)

0
1
2
10
12
13
100
101
102
110
112
113

----------

0
1
2
10
12
13
100
101
102
110
112
113


In [23]:
# slices
def f(x, y):
    return 10*x+y

# Creating an array from the function from above
b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [24]:
# Slices
print(b[0:5, 1])  # every lines of the second column
print()
print(b[:, 1])  # every lines of the second column

print()
print('----------')
print()

print(b[1:3, : ]) # 2nd and 3rd lines of all columns

print()
print('----------')
print()

print(b[2, 1:3]) # 3rd line, 2nd and 3rd columns

print()
print('----------')
print()

print(b[2, 2:4]) # 3rd line, 2 last columns
print()
print(b[2, -2:]) # 3rd line, 2 last columns

[ 1 11 21 31 41]

[ 1 11 21 31 41]

----------

[[10 11 12 13]
 [20 21 22 23]]

----------

[21 22]

----------

[22 23]

[22 23]


In [25]:
# Masks
# Create a table
a = np.arange(12).reshape(3,4)
display(a)
# Create a mask
b = a > 4
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
# Use the mask to select elements of the matrix
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [27]:
# This is the shape of a matrix

c = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

c.shape

(4, 3)

In [28]:
# A matrix is an array of the second dimension (order):
len(c.shape)

2