1 - Import numpy

In [1]:
import numpy as np

In [4]:
u_vec = np.array([2, 9, -1])
v_vec = np.array([1, 5, 3])
print("vector u:", u_vec.shape)
print(u_vec)
print("vector v:", v_vec.shape)
print (v_vec)

u_vec + v_vec

vector u: (3,)
[ 2  9 -1]
vector v: (3,)
[1 5 3]


array([ 3, 14,  2])

In [6]:
u_vec = np.array([10, -2, 1])
v_vec = np.array([4, 3, 2])
u_vec - v_vec

array([ 6, -5, -1])

In [8]:
u_vec = np.array([1, -2, 2])
v_vec = np.array([2, 1, 0])
4*(u_vec + v_vec)

array([12, -4,  8])

In [9]:
u_vec = np.array([1, 2, 3, 4])
v_vec = np.array([-1, 2, -3, 4])
print("Norm of u:")
print(np.linalg.norm(u_vec))
print("Norm of v:")
print(np.linalg.norm(v_vec))

Norm of u:
5.477225575051661
Norm of v:
5.477225575051661


In [10]:
A_mat = np.array([[1, 2, 3],
                  [2, 1, 4],
                  [3, 4, 1]])

B_mat = np.array([[2, 3, 4],
                  [3, 2, 5],
                  [4, 5, 2]])
A_mat + B_mat

array([[3, 5, 7],
       [5, 3, 9],
       [7, 9, 3]])

In [13]:
2*A_mat-B_mat

array([[0, 1, 2],
       [1, 0, 3],
       [2, 3, 0]])

In [14]:
A_mat = np.array([[1, 0, 2],
                  [2, 1, 0],
                  [1, 2, 1]])

B_mat = np.array([[2, 0, 0],
                  [1, 2, 0],
                  [0, 1, 2]])

print("AB: ")
print(A_mat.dot(B_mat))
print()
print("BA: ")
print(B_mat.dot(A_mat))


AB: 
[[2 2 4]
 [5 2 0]
 [4 5 2]]

BA: 
[[2 0 4]
 [5 2 2]
 [4 5 2]]


In [17]:
A_mat = np.array([[1, 0],
                  [2, 1],
                  [1, 2]])

B_mat = np.array([[2, 0, 0],
                  [1, 2, 0]])

print("AB: ")
print(A_mat.dot(B_mat))
print()
print("BA: ")
print(B_mat.dot(A_mat))

AB: 
[[2 0 0]
 [5 2 0]
 [4 4 0]]

BA: 
[[2 0]
 [5 2]]


In [20]:
A_mat = np.array([[1, 0, 2],
                  [2, 1, 0],
                  [1, 2, 1]])

B_mat = np.array([-1, 1, 2])

y_vec = A_mat @ B_mat
y_vec

array([ 3, -1,  3])

In [24]:
A_mat = np.array([2, -3, -1])
B_mat = np.array([3, 1, 3])
print("dot product:", B_mat.dot(A_mat))

dot product: 0


In [32]:
A_mat = np.array([4, -2, -1])
B_vec = np.array([-1, -1/2, 1/4])

print("Element-wise division: ", A_mat/B_vec)

Element-wise division:  [-4.  4. -4.]


In [33]:
A_mat = np.array([1, 2])
B_vec = np.array([-2, 1])
C_vec = np.array([-1, 3])

print(A_mat)
print("C_vec - B_vec", C_vec - B_vec)

[1 2]
C_vec - B_vec [1 2]


In [34]:
A = np.array([[2, 1, 0],
              [1, 2, 1],
              [0, 1, 2]])

c = np.array([2, 0,1])

In [35]:
x = np.linalg.solve(A, c)
print("Solution: x = ", x)

Solution: x =  [ 1.75 -1.5   1.25]


In [36]:
A_inv = np.linalg.inv(A)
print("Inverse of A: ")
print(A_inv)
print()

print("Solution: x = ", A_inv @ c)

Inverse of A: 
[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

Solution: x =  [ 1.75 -1.5   1.25]


In [37]:
A = np.array([[3, -1],
              [2, 0]])

u = np.array([1, 1])
v = np.array([1, 2])

print("Au: ", A @ u)
print("Av: ", A @ v)

Au:  [2 2]
Av:  [1 2]


In [38]:
eigenvals, eigenvecs = np.linalg.eig(A)
print("eigenvectors of A:")
print(eigenvecs)
print("eigenvalues of A:")
print(eigenvals)

eigenvectors of A:
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]
eigenvalues of A:
[2. 1.]
